permissions:
  contents: read

jobs:
  lint:
    env:
      FORCE_COLOR: '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: ./.github/actions/prepare
      - run: npm run lint

name: Lint

on: [push, pull_request]
