name: Node CI

on:
  push:
    paths-ignore:
      - '!.github/actions/prepare/**'
      - '!.github/workflows/nodejs.yml'
      - '.claude/**'
      - '.commitlintrc.js'
      - '.config/eslint-rules/**'
      - '.config/typedoc*.js'
      - '.editorconfig'
      - '.github/**'
      - '.husky/**'
      - '.markdownlint-cli2.yaml'
      - '.prettierignore'
      - '.release-please-manifest.json'
      - '.vscode/**'
      - '.wallaby.js'
      - '**/CHANGELOG.md'
      - '**/README.md'
      - 'assets/**'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'cspell.json'
      - 'eslint.config.js'
      - 'knip.json'
      - 'LICENSE.md'
      - 'release-please-config.json'
      - 'site/**'
  pull_request:
    paths-ignore:
      - '!.github/actions/prepare/**'
      - '!.github/workflows/nodejs.yml'
      - '.claude/**'
      - '.commitlintrc.js'
      - '.config/eslint-rules/**'
      - '.config/typedoc*.js'
      - '.editorconfig'
      - '.github/**'
      - '.husky/**'
      - '.markdownlint-cli2.yaml'
      - '.prettierignore'
      - '.release-please-manifest.json'
      - '.vscode/**'
      - '.wallaby.js'
      - '**/CHANGELOG.md'
      - '**/README.md'
      - 'assets/**'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'cspell.json'
      - 'eslint.config.js'
      - 'knip.json'
      - 'LICENSE.md'
      - 'release-please-config.json'
      - 'site/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    env:
      FORCE_COLOR: '1'
    name: Build & Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node-version: '^20.19.0'
          - node-version: '^22.12.0'
          - node-version: '^24.0.0'
          - node-version: '^26.0.0'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build
      - name: Test (Node v20.x)
        if: startsWith(matrix.node-version, '^20')
        # CAUTION: this only works in POSIX environments
        run: npm run test:node20
      - name: Test
        if: ${{ !startsWith(matrix.node-version, '^20') }}
        run: npm test
