name: Node CI

on:
  push:
    paths-ignore:
      - '!.github/actions/prepare/**'
      - '!.github/workflows/nodejs.yml'
      - '.claude/**'
      - '.commitlintrc.js'
      - '.config/eslint-rules/**'
      - '.config/typedoc*.js'
      - '.editorconfig'
      - '.github/**'
      - '.husky/**'
      - '.markdownlint-cli2.yaml'
      - '.prettierignore'
      - '.release-please-manifest.json'
      - '.vscode/**'
      - '.wallaby.js'
      - '**/CHANGELOG.md'
      - '**/README.md'
      - 'assets/**'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'cspell.json'
      - 'eslint.config.js'
      - 'knip.json'
      - 'LICENSE.md'
      - 'release-please-config.json'
      - 'site/**'
  pull_request:
    paths-ignore:
      - '!.github/actions/prepare/**'
      - '!.github/workflows/nodejs.yml'
      - '.claude/**'
      - '.commitlintrc.js'
      - '.config/eslint-rules/**'
      - '.config/typedoc*.js'
      - '.editorconfig'
      - '.github/**'
      - '.husky/**'
      - '.markdownlint-cli2.yaml'
      - '.prettierignore'
      - '.release-please-manifest.json'
      - '.vscode/**'
      - '.wallaby.js'
      - '**/CHANGELOG.md'
      - '**/README.md'
      - 'assets/**'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'cspell.json'
      - 'eslint.config.js'
      - 'knip.json'
      - 'LICENSE.md'
      - 'release-please-config.json'
      - 'site/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    env:
      FORCE_COLOR: '1'
    name: Build & Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node-version: '^22.22.1'
          - node-version: '^24.0.0'
          - node-version: '^26.0.0'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ matrix.node-version }}
      - parallel:
          - name: Run Tests
            run: npm run test:ci
          - name: Run tsd
            run: npm run test:types
